import type { GitStatusEntry } from '@pierre/trees';
import { PullRequestBadgeStatus } from '@code-review-app/shared';
import type {
  AccountVisibilitySettings,
  AppearanceBackgroundInput,
  AppearanceBackgroundSettings,
  CreatePendingReviewGlobalInput,
  CreatePendingReviewReplyInput,
  CreatePendingReviewThreadInput,
  CreatePullRequestReviewCommentInput,
  DeletePullRequestReviewCommentInput,
  DeletePendingReviewCommentInput,
  DiffDataMode,
  DiffDataSettings,
  DiscardPendingReviewInput,
  ForgeProviderKind,
  NamespaceSummary,
  OverviewPullRequestSummary,
  PendingReviewComment,
  PendingReviewSession,
  PendingReviewState,
  PendingReviewSubmitAction,
  PublishPendingReviewInput,
  PullRequestApprovalActor,
  PullRequestApprovalRemoveStrategy,
  PullRequestApprovalState,
  PrFileChangeType,
  PrFileContents,
  PrPatch,
  ProviderAccount,
  ProviderAuthStatus,
  ProviderAuthStatusKind,
  ProviderProfile,
  PullRequestQualityFinding,
  PullRequestQualityFindingAnchorState,
  PullRequestQualityFindingSeverity,
  PullRequestQualityFindingSourceType,
  PullRequestQualityFindingStatus,
  PullRequestQualityReport,
  PullRequestQualityReportStatus,
  PullRequestQualitySummary,
  PullRequestSearchState,
  PullRequestSummary,
  ReplyToPullRequestReviewCommentInput,
  RepoIdentity,
  RepoSummary,
  ReviewCommentSide,
  ReviewEditorMode,
  ReviewEditorSettings,
  SelectedPullRequest,
  SetPullRequestReviewThreadResolvedInput,
  ThemePreference,
  ThemePreferenceSettings,
  TrackedPullRequestOrderEntry,
  UpdatePendingReviewCommentInput,
  UpdatePullRequestReviewCommentInput,
  ViewerLogin,
} from '@code-review-app/shared';

type FileStatsEntry = {
  additions: number;
  deletions: number;
  status: GitStatusEntry['status'];
};

export { PullRequestBadgeStatus };
export type {
  AccountVisibilitySettings,
  AppearanceBackgroundInput,
  AppearanceBackgroundSettings,
  CreatePendingReviewGlobalInput,
  CreatePendingReviewReplyInput,
  CreatePendingReviewThreadInput,
  CreatePullRequestReviewCommentInput,
  DeletePullRequestReviewCommentInput,
  DeletePendingReviewCommentInput,
  DiffDataMode,
  DiffDataSettings,
  DiscardPendingReviewInput,
  FileStatsEntry,
  ForgeProviderKind,
  NamespaceSummary,
  OverviewPullRequestSummary,
  PendingReviewComment,
  PendingReviewSession,
  PendingReviewState,
  PendingReviewSubmitAction,
  PublishPendingReviewInput,
  PullRequestApprovalActor,
  PullRequestApprovalRemoveStrategy,
  PullRequestApprovalState,
  PrFileChangeType,
  PrFileContents,
  PrPatch,
  ProviderAccount,
  ProviderAuthStatus,
  ProviderAuthStatusKind,
  ProviderProfile,
  PullRequestQualityFinding,
  PullRequestQualityFindingAnchorState,
  PullRequestQualityFindingSeverity,
  PullRequestQualityFindingSourceType,
  PullRequestQualityFindingStatus,
  PullRequestQualityReport,
  PullRequestQualityReportStatus,
  PullRequestQualitySummary,
  PullRequestSearchState,
  PullRequestSummary,
  ReplyToPullRequestReviewCommentInput,
  RepoIdentity,
  RepoSummary,
  ReviewCommentSide,
  ReviewEditorMode,
  ReviewEditorSettings,
  SelectedPullRequest,
  SetPullRequestReviewThreadResolvedInput,
  ThemePreference,
  ThemePreferenceSettings,
  TrackedPullRequestOrderEntry,
  UpdatePendingReviewCommentInput,
  UpdatePullRequestReviewCommentInput,
  ViewerLogin,
};
